baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mugencode'

BookMenuBundle = '/menu'
theme = 'hugo-book'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
