baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mugencode'

theme = 'mugencode'

cleanDestinationDir = true


[menus]
  [[menus.main]]
    name = 'About'
    URL = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    URL = '/posts/'
    weight = 20

[params]
  BookToC = true
  BookLogo = "/images/logo.png"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1